---
title: "Machine Learning - Week 2 - Lab 1"
author: "Amol Gote"
date: "9/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library_setup, MESSAGE = FALSE}
set.seed(123)
library(tidyverse)
library(caret)
```

```{r load_data}
medical_ds <- read.csv("./data/data.csv")
```

```{r data_summary, MESSAGE = FALSE}
summary(medical_ds)
```
```{r ds_info, MESSAGE = FALSE}
nrow(medical_ds)
```

```{r, final_dataset, MESSAGE = FALSE}
medical_ds_1 <- medical_ds[,c(
  "age", "race", "gender", "admission_type_id","discharge_disposition_id", "admission_source_id", "time_in_hospital","num_lab_procedures",
  "num_procedures","num_medications","number_outpatient","number_emergency","number_inpatient",
  "diag_1","diag_2","diag_3","number_diagnoses","change","max_glu_serum","A1Cresult","metformin",
  "glimepiride","glipizide","glyburide","pioglitazone","rosiglitazone",
  "insulin","readmitted"
  )]
summary(medical_ds_1)
```

```{r dataset_na_removal}
medical_ds_2 <- na.omit(medical_ds_1, cols = c("race","gender", "diag_1", "diag_2", "diag_3"))
nrow(medical_ds_2)
medical_ds_3 <- medical_ds_2 %>%
  filter(!(discharge_disposition_id %in% c(11,19,20,21)))
nrow(medical_ds_3)
medical_ds_3 <- medical_ds_3 %>%
  filter(gender != 'Unknown/Invalid')
nrow(medical_ds_3)
summary(medical_ds_3)
```

```{r feature_engg_1}
medical_ds_3$readmitted_enc[medical_ds_3$readmitted == '<30'] <- 1
medical_ds_3$readmitted_enc[medical_ds_3$readmitted == '>30'] <- 1
medical_ds_3$readmitted_enc[medical_ds_3$readmitted == 'NO'] <- 0
medical_ds_3$readmitted_enc <- factor(medical_ds_3$readmitted_enc)
```

```{r adjust_age}
medical_ds_3$age_enc[medical_ds_3$age == '[0-10)']   <- 'Young'
medical_ds_3$age_enc[medical_ds_3$age == '[10-20)']  <- 'Young'
medical_ds_3$age_enc[medical_ds_3$age == '[20-30)']  <- 'Young'
medical_ds_3$age_enc[medical_ds_3$age == '[30-40)']  <- 'Young'
medical_ds_3$age_enc[medical_ds_3$age == '[40-50)']  <- 'Middle-aged'
medical_ds_3$age_enc[medical_ds_3$age == '[50-60)']  <- 'Middle-aged'
medical_ds_3$age_enc[medical_ds_3$age == '[60-70)']  <- 'Old'
medical_ds_3$age_enc[medical_ds_3$age == '[70-80)']  <- 'Old'
medical_ds_3$age_enc[medical_ds_3$age == '[80-90)']  <- 'Older'
medical_ds_3$age_enc[medical_ds_3$age == '[90-100)'] <- 'Older'
medical_ds_3$age_enc <- factor(medical_ds_3$age_enc)
summary(medical_ds_3)
```


```{r gender}
medical_ds_3$gender <- factor(medical_ds_3$gender)
```

```{r race}
medical_ds_3$race <- factor(medical_ds_3$race)
```

```{r admission_source}
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id <= 3] <- "Referral"

medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 4] <- "Transfer"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 5] <- "Transfer"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 6] <- "Transfer"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 10] <- "Transfer"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 18] <- "Transfer"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 22] <- "Transfer"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 25] <- "Transfer"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 26] <- "Transfer"

medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 11] <- "Birth"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 12] <- "Birth"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 13] <- "Birth"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 14] <- "Birth"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 23] <- "Birth"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 24] <- "Birth"

medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 7] <- "Misc"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 8] <- "Misc"

medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 9] <- "Unknown"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 15] <- "Unknown"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 17] <- "Unknown"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 19] <- "Unknown"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 20] <- "Unknown"
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 21] <- "Unknown"
medical_ds_3$admission_source_id_enc <- factor(medical_ds_3$admission_source_id_enc)
```

```{r admission_type_id}
medical_ds_3$admission_type_id_enc[medical_ds_3$admission_type_id == 1] <- "Emergency"
medical_ds_3$admission_type_id_enc[medical_ds_3$admission_type_id == 2] <- "Urgent"
medical_ds_3$admission_type_id_enc[medical_ds_3$admission_type_id == 3] <- "Elective"
medical_ds_3$admission_type_id_enc[medical_ds_3$admission_type_id >= 4] <- "Other"
medical_ds_3$admission_type_id_enc <- factor(medical_ds_3$admission_type_id_enc)
```


```{r admission_type_id}
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 6] <- "Discharged"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 8] <- "Discharged"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 15] <- "Discharged"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 16] <- "Discharged"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 17] <- "Discharged"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 22] <- "Discharged"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 23] <- "Discharged"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 24] <- "Discharged"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 27] <- "Discharged"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 28] <- "Discharged"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 29] <- "Discharged"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 30] <- "Discharged"

medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 13] <- "Hospice"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 14] <- "Hospice"

medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 7] <- "Misc"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 9] <- "Misc"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 10] <- "Misc"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 12] <- "Misc"

medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 18] <- "Unknown"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 25] <- "Unknown"
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 26] <- "Unknown"
medical_ds_3$discharge_disposition_id_enc <- factor(medical_ds_3$discharge_disposition_id_enc)
```

```{r factor_other}
medical_ds_3$max_glu_serum <- factor(medical_ds_3$max_glu_serum)
medical_ds_3$A1Cresult <- factor(medical_ds_3$A1Cresult)
medical_ds_3$change <- factor(medical_ds_3$change)
```

```{r converttonumeric}
#medical_ds_3$diag_1_enc <- medical_ds_3$diag_1
#library(dplyr)
#medical_ds_3 %>% 
#  mutate(diag_1_enc=ifelse(diag_1_enc=='E909','001',diag_1_enc))

#temp <- medical_ds_3 %>%
#  mutate(diag_1_enc == "E909")

#medical_ds_3[medical_ds_3$diag_1_enc=='5', "diag_1_enc"] <- '100'
#medical_ds_3$diag_1_enc <- factor(medical_ds_3$diag_1_enc)
#medical_ds_3$diag_1_enc <- as.numeric(medical_ds_3$diag_1_enc)
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "E909"] <- "001"
##medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V25"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V26"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V43"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V45"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V51"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V53"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V54"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V55"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V56"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V57"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V58"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V60"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V63"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V66"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V67"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V70"] <- "1"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1_enc == "V71"] <- "1"
#summary(medical_ds_3$diag_1_enc)
#temp <- medical_ds_3 %>%
#  filter(diag_1_enc == "E909")
#nrow(temp)
#temp
```

```{r diagnosis_code_1_encoding, MESSAGE=FALSE}
#medical_ds_3$diag_1_enc <- as.numeric(medical_ds_3$diag_1_enc)
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 390 & medical_ds_3$diag_1 <= 459] <- "Circulatory"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 == 785] <- "Circulatory"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 460 & medical_ds_3$diag_1 <= 519] <- "Respiratory"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 == 786] <- "Respiratory"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 520 & medical_ds_3$diag_1 <= 579] <- "Digestive"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 == 787] <- "Digestive"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 250.00 & medical_ds_3$diag_1 <= 250.99] <- "4"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 800 & medical_ds_3$diag_1 <= 999] <- "Injury"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 710 & medical_ds_3$diag_1 <= 739] <- "Musculoskeletal"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 580 & medical_ds_3$diag_1 <= 629] <- "Genitourinary"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 == 788] <- "Genitourinary"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 140 & medical_ds_3$diag_1 <= 239] <- "8"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 == 780 | medical_ds_3$diag_1 == 782 | medical_ds_3$diag_1 == 781 | medical_ds_3$diag_1 == 784] <- "Other"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 790 & medical_ds_3$diag_1 <= 799] <- "Other"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 240 & medical_ds_3$diag_1 <= 249] <- "Other"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 251 & medical_ds_3$diag_1 <= 279] <- "Other"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 680 & medical_ds_3$diag_1 <= 709] <- "Other"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 1 & medical_ds_3$diag_1 <= 139] <- "Other"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 290 & medical_ds_3$diag_1 <= 319] <- "Other"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 280 & medical_ds_3$diag_1 <= 289] <- "Other"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 320 & medical_ds_3$diag_1 <= 359] <- "Other"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 630 & medical_ds_3$diag_1 <= 679] <- "Other"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 360 & medical_ds_3$diag_1 <= 389] <- "Other"
#medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 740 & medical_ds_3$diag_1 <= 759] <- "Other"
#levels(medical_ds_3$diag_1_enc)
```

```{r final_dataset}
final_medical_ds_1 <- medical_ds_3
summary(final_medical_ds_1)
```


```{r data_partition, MESSAGE=FALSE}
# split the data into training and (held-out) test sets
training_ind <- createDataPartition(final_medical_ds_1$readmitted_enc,
p = 0.75,
list = FALSE,
times = 1)
training_set <- final_medical_ds_1[training_ind, ]
test_set <- final_medical_ds_1[-training_ind, ]
```

```{r}
summary(training_set)
```

```{r target_encoding, MESSAGE=FALSE}

threshold <- 250
target_enc_train <- function(variable, level) {
  training_set$readmitted_enc <- as.numeric(as.vector(training_set$readmitted_enc))
  train_avg_target <- mean(training_set[, "readmitted_enc"])
  if (nrow(training_set[training_set[, variable]==level, ])==0) {
    return(train_avg_target)
  } else {
    level_num_obs <- nrow(training_set[training_set[, variable]==level,])
    level_avg_target <- mean(training_set[training_set[, variable]==level,
    "readmitted_enc"])
    return((level_num_obs*level_avg_target+threshold*train_avg_target)/(level_num_obs+threshold))
  }
}
age_target <- mapply(target_enc_train, variable = "age_enc", level = levels(training_set$age_enc), USE.NAMES = FALSE)
names(age_target) <- levels(training_set$age_enc)
training_set$age_target <- 0
for (level in levels(training_set$age_enc)) {
  training_set[training_set[, "age_enc"]==level, "age_target"] <- age_target[level]
}

test_set$age_target <- 0
for (level in levels(training_set$age_enc)) {
  test_set[test_set[, "age_enc"]==level, "age_target"] <- age_target[level]
}


#gender_target <- mapply(target_enc_train, variable = "gender", level = levels(training_set$gender), USE.NAMES = FALSE)
#names(gender_target) <- levels(training_set$gender)
#training_set$gender_target <- 0
#for (level in levels(training_set$gender)) {
#  training_set[training_set[, "gender"]==level, "gender_target"] <- gender_target[level]
#}

#test_set$gender_target <- 0
#for (level in levels(training_set$gender)) {
#  test_set[test_set[, "gender"]==level, "gender_target"] <- gender_target[level]
#}


race_target <- mapply(target_enc_train, variable = "race", level = levels(training_set$race), USE.NAMES = FALSE)
names(race_target) <- levels(training_set$race)
training_set$race_target <- 0
for (level in levels(training_set$race)) {
  training_set[training_set[, "race"]==level, "race_target"] <- race_target[level]
}

test_set$race_target <- 0
for (level in levels(training_set$race)) {
  test_set[test_set[, "race"]==level, "race_target"] <- race_target[level]
}


admission_source_id_target <- mapply(target_enc_train, variable = "admission_source_id_enc", level = levels(training_set$admission_source_id_enc), USE.NAMES = FALSE)
names(admission_source_id_target) <- levels(training_set$admission_source_id_enc)
training_set$admission_source_id_target <- 0
for (level in levels(training_set$admission_source_id_enc)) {
  training_set[training_set[, "admission_source_id_enc"]==level, "admission_source_id_target"] <- admission_source_id_target[level]
}

test_set$admission_source_id_target <- 0
for (level in levels(training_set$admission_source_id_enc)) {
  test_set[test_set[, "admission_source_id_enc"]==level, "admission_source_id_target"] <- admission_source_id_target[level]
}

admission_type_id_target <- mapply(target_enc_train, variable = "admission_type_id_enc", level = levels(training_set$admission_type_id_enc), USE.NAMES = FALSE)
names(admission_type_id_target) <- levels(training_set$admission_type_id_enc)
training_set$admission_type_id_target <- 0
for (level in levels(training_set$admission_type_id_enc)) {
  training_set[training_set[, "admission_type_id_enc"]==level, "admission_type_id_target"] <- admission_type_id_target[level]
}

test_set$admission_type_id_target <- 0
for (level in levels(training_set$admission_type_id_enc)) {
  test_set[test_set[, "admission_type_id_enc"]==level, "admission_type_id_target"] <- admission_type_id_target[level]
}

discharge_disposition_id_target <- mapply(target_enc_train, 
                                          variable = "discharge_disposition_id_enc", level = levels(training_set$discharge_disposition_id_enc), USE.NAMES = FALSE)
names(discharge_disposition_id_target) <- levels(training_set$discharge_disposition_id_enc)
training_set$discharge_disposition_id_target <- 0
for (level in levels(training_set$discharge_disposition_id_enc)) {
  training_set[training_set[, "discharge_disposition_id_enc"]==level, "discharge_disposition_id_target"] <- discharge_disposition_id_target[level]
}

test_set$discharge_disposition_id_target <- 0
for (level in levels(training_set$discharge_disposition_id_enc)) {
  test_set[test_set[, "discharge_disposition_id_enc"]==level, "discharge_disposition_id_target"] <- discharge_disposition_id_target[level]
}


max_glu_serum_target <- mapply(target_enc_train, variable = "max_glu_serum", level = levels(training_set$max_glu_serum), USE.NAMES = FALSE)
names(max_glu_serum_target) <- levels(training_set$max_glu_serum)
training_set$max_glu_serum_target <- 0
for (level in levels(training_set$max_glu_serum)) {
  training_set[training_set[, "max_glu_serum"]==level, "max_glu_serum_target"] <- max_glu_serum_target[level]
}

test_set$max_glu_serum_target <- 0
for (level in levels(training_set$max_glu_serum)) {
  test_set[test_set[, "max_glu_serum"]==level, "max_glu_serum_target"] <- max_glu_serum_target[level]
}

A1Cresult_target <- mapply(target_enc_train, variable = "A1Cresult", level = levels(training_set$A1Cresult), USE.NAMES = FALSE)
names(A1Cresult_target) <- levels(training_set$A1Cresult)
training_set$A1Cresult_target <- 0
for (level in levels(training_set$A1Cresult)) {
  training_set[training_set[, "A1Cresult"]==level, "A1Cresult_target"] <- A1Cresult_target[level]
}

test_set$A1Cresult_target <- 0
for (level in levels(training_set$A1Cresult)) {
  test_set[test_set[, "A1Cresult"]==level, "A1Cresult_target"] <- A1Cresult_target[level]
}

#change_target <- mapply(target_enc_train, variable = "change", level = levels(training_set$change), USE.NAMES = FALSE)
#names(change_target) <- levels(training_set$change)
#training_set$change_target <- 0
#for (level in levels(training_set$change)) {
#  training_set[training_set[, "change"]==level, "change_target"] <- change_target[level]
#}

#test_set$change_target <- 0
#for (level in levels(training_set$change)) {
#  test_set[test_set[, "change"]==level, "change_target"] <- change_target[level]
#}

```

```{r one_hot_encoding, MESSAGE=FALSE}
onehot_encoder <- dummyVars(~ gender + change, final_medical_ds_1[, c("gender", "change")])
onehot_enc_training <- predict(onehot_encoder, training_set[, c("gender", "change")])
training_set <- cbind(training_set, onehot_enc_training)
onehot_enc_test <- predict(onehot_encoder, test_set[, c("gender", "change")])
test_set <- cbind(test_set, onehot_enc_test)
```


```{r summary}
summary(test_set)
```

```{r}
summary(training_set)
summary(test_set)
```

```{r, nnnet_subset}
training_subset_ds <- training_set[sample(nrow(training_set), 1000),]
nrow(training_subset_ds)

test_subset_ds <- test_set[sample(nrow(test_set), 250),]
nrow(test_subset_ds)
```
```{r peak_data}
head(training_subset_ds)
head(test_subset_ds)
```


```{r, remove_columns}
colnames(training_subset_ds)
```

```{r, remove_columns_1}
training_subset_ds_final <- training_subset_ds[,c(
  "age_target", "race_target", 
  "admission_type_id_target",
  "discharge_disposition_id_target",
  "admission_source_id_target",
  "max_glu_serum_target",
  "A1Cresult_target",
  "time_in_hospital", "num_lab_procedures",           
  "num_procedures", "num_medications","number_outpatient","number_emergency",
  "number_inpatient", "number_diagnoses",
  "gender.Female", "gender.Male", "change.Ch","change.No",
  "readmitted_enc"
  )]

test_subset_ds_final <- test_subset_ds[,c(
  "age_target", "race_target",
  "admission_type_id_target",
  "discharge_disposition_id_target",
  "admission_source_id_target",
  "max_glu_serum_target",
  "A1Cresult_target",
  "time_in_hospital", "num_lab_procedures",           
  "num_procedures", "num_medications","number_outpatient","number_emergency",
  "number_inpatient", "number_diagnoses",
  "gender.Female", "gender.Male", "change.Ch","change.No",
  "readmitted_enc"
  )]

```

```{r colnames}
summary(training_subset_ds_final)
```
```{r colnames}
colnames(training_subset_ds_final)
```

```{r, SCALE_VARIABLES}
num_var_start_index <- 8
num_var_end_index <- 15
target_var_index <- 20
test_subset_ds_final[, num_var_start_index:num_var_end_index] <- scale(test_subset_ds_final[, num_var_start_index:num_var_end_index], 
                                       center = apply(training_subset_ds_final[, num_var_start_index:num_var_end_index], 2, mean), 
                                       scale = apply(training_subset_ds_final[, num_var_start_index:num_var_end_index], 2, sd))
training_subset_ds_final[, num_var_start_index:num_var_end_index] <- scale(training_subset_ds_final[, num_var_start_index:num_var_end_index])
levels(training_subset_ds_final$readmitted_enc)[levels(training_subset_ds_final$readmitted_enc) == 1] <- "Yes"
levels(training_subset_ds_final$readmitted_enc)[levels(training_subset_ds_final$readmitted_enc) == 0] <- "No"
```

```{r}
#colnames()
```

```{r peak_data}
head(training_subset_ds_final)
head(test_subset_ds_final)
```


```{r random_forest}
modelLookup("rf")
recommended_mtry <- floor(sqrt(ncol(training_subset_ds_final[,-1*c(target_var_index:target_var_index)])))
rfGrid <- expand.grid(mtry = c(recommended_mtry-2, recommended_mtry, recommended_mtry+2))
```

```{r random_forest_1}

rfControl <- trainControl(method = "oob", classProbs = TRUE)
rf_onehot_model <- train(x = training_subset_ds_final[, -1*c(target_var_index:target_var_index)], y = training_subset_ds_final[, target_var_index],
                  method = "rf",
                  tuneGrid = rfGrid,
                  trControl = rfControl,
                  ntree = 10,
                  importance = TRUE,
                  trace = FALSE)

```

```{r prediction}
test_subset_ds_final$prediction_onehot <- predict(rf_onehot_model, newdata = test_subset_ds_final[, -1*c(target_var_index:target_var_index)])
class_probabilities <- predict(rf_onehot_model, newdata = test_subset_ds_final[, -1*c(target_var_index:target_var_index)], type = "prob")
test_subset_ds_final$class_probabilities_onehot <- class_probabilities$Yes
```

```{r evaluate}
rocr_pred <- prediction(test_subset_ds_final$class_probabilities_onehot, test_subset_ds_final$readmitted_enc)
rocr_roc <- performance(rocr_pred, measure = "tpr", x.measure = "fpr")
plot(rocr_roc,
colorize = TRUE,
print.cutoffs.at = seq(0, 1, by = 0.1),
text.adj = c(-0.5, 1),
lwd = 2)
abline(a = 0, b = 1)

```

```{r auc_value}
rocr_auc <- performance(rocr_pred, measure = "auc")
auc <- rocr_auc@y.values[[1]]
auc
```

```{r feature_importance}
rf_varImp <- varImp(rf_onehot_model, type = 2)
plot(rf_varImp, top = 25)
```