---
title: "Machine Learning - Week 2 - Lab 1"
author: "Amol Gote"
date: "9/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library_setup, MESSAGE = FALSE}
set.seed(123)
library(tidyverse)
library(caret)
```

```{r load_data}
medical_ds <- read.csv("./data/data.csv")
```

```{r data_summary, MESSAGE = FALSE}
summary(medical_ds)
```
```{r ds_info, MESSAGE = FALSE}
nrow(medical_ds)
```

```{r, final_dataset, MESSAGE = FALSE}
medical_ds_1 <- medical_ds[,c(
  "age", "race", "gender", "admission_type_id","discharge_disposition_id", "admission_source_id", "time_in_hospital","num_lab_procedures",
  "num_procedures","num_medications","number_outpatient","number_emergency","number_inpatient",
  "diag_1","diag_2","diag_3","number_diagnoses","change","max_glu_serum","A1Cresult","metformin","repaglinide",
  "nateglinide","chlorpropamide","glimepiride","glipizide","glyburide","pioglitazone","rosiglitazone",
  "acarbose","miglitol","insulin","glyburide.metformin","readmitted"
  )]
summary(medical_ds_1)
```

```{r dataset_na_removal}
medical_ds_2 <- na.omit(medical_ds_1, cols = c("race","gender", "diag_1", "diag_2", "diag_3"))
nrow(medical_ds_2)
medical_ds_3 <- medical_ds_2 %>%
  filter(!(discharge_disposition_id %in% c(11,19,20,21)))
nrow(medical_ds_3)
medical_ds_3 <- medical_ds_3 %>%
  filter(gender != 'Unknown/Invalid')
nrow(medical_ds_3)
summary(medical_ds_3)
```

```{r age_plot}
ggplot(data = medical_ds_3)+
  geom_bar(aes(x = age))+
  theme_minimal() 
```

```{r age_plot}
ggplot(data = medical_ds_3)+
  geom_bar(aes(x = admission_type_id))+
  theme_minimal() 
```




```{r age_consolidation, MESSAGE=FALSE}
medical_ds_3$age_ordinal[medical_ds_3$age == '[0-10)']   <- 0
medical_ds_3$age_ordinal[medical_ds_3$age == '[10-20)']  <- 0
medical_ds_3$age_ordinal[medical_ds_3$age == '[20-30)']  <- 0
medical_ds_3$age_ordinal[medical_ds_3$age == '[30-40)']  <- 0
medical_ds_3$age_ordinal[medical_ds_3$age == '[40-50)']  <- 1
medical_ds_3$age_ordinal[medical_ds_3$age == '[50-60)']  <- 1
medical_ds_3$age_ordinal[medical_ds_3$age == '[60-70)']  <- 2
medical_ds_3$age_ordinal[medical_ds_3$age == '[70-80)']  <- 2
medical_ds_3$age_ordinal[medical_ds_3$age == '[80-90)']  <- 3
medical_ds_3$age_ordinal[medical_ds_3$age == '[90-100)'] <- 3


medical_ds_3$gender_enc[medical_ds_3$gender == 'Male'] <- 1
medical_ds_3$gender_enc[medical_ds_3$gender == 'Female'] <- 0

medical_ds_3$race_enc[medical_ds_3$race == 'Caucasian'] <- 1
medical_ds_3$race_enc[medical_ds_3$race == 'AfricanAmerican'] <- 2
medical_ds_3$race_enc[medical_ds_3$race == 'Hispanic'] <- 3
medical_ds_3$race_enc[medical_ds_3$race == 'Asian'] <- 5
medical_ds_3$race_enc[medical_ds_3$race == 'Other'] <- 4

medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id <= 3] <- 1

medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 4] <- 2
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 5] <- 2
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 6] <- 2
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 10] <- 2
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 18] <- 2
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 22] <- 2
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 25] <- 2
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 26] <- 2

medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 11] <- 3
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 12] <- 3
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 13] <- 3
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 14] <- 3
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 23] <- 3
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 24] <- 3

medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 7] <- 4
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 8] <- 4

medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 9] <- 5
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 15] <- 5
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 17] <- 5
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 19] <- 5
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 20] <- 5
medical_ds_3$admission_source_id_enc[medical_ds_3$admission_source_id == 21] <- 5

medical_ds_3$admission_type_id_enc[medical_ds_3$admission_type_id == 1] <- 1
medical_ds_3$admission_type_id_enc[medical_ds_3$admission_type_id == 2] <- 2
medical_ds_3$admission_type_id_enc[medical_ds_3$admission_type_id == 3] <- 3
medical_ds_3$admission_type_id_enc[medical_ds_3$admission_type_id >= 4] <- 4

medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 6] <- 1
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 8] <- 1
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 15] <- 1
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 16] <- 1
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 17] <- 1
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 22] <- 1
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 23] <- 1
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 24] <- 1
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 27] <- 1
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 28] <- 1
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 29] <- 1
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 30] <- 1

medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 13] <- 2
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 14] <- 2

medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 7] <- 3
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 9] <- 3
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 10] <- 3
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 12] <- 3

medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 18] <- 4
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 25] <- 4
medical_ds_3$discharge_disposition_id_enc[medical_ds_3$discharge_disposition_id <= 26] <- 4


medical_ds_3$max_glu_serum_enc[medical_ds_3$max_glu_serum == 'None'] <- 0
medical_ds_3$max_glu_serum_enc[medical_ds_3$max_glu_serum == 'Norm'] <- 1
medical_ds_3$max_glu_serum_enc[medical_ds_3$max_glu_serum == '>200'] <- 2
medical_ds_3$max_glu_serum_enc[medical_ds_3$max_glu_serum == '>300'] <- 3


medical_ds_3$A1Cresult_enc[medical_ds_3$A1Cresult == 'None'] <- 0
medical_ds_3$A1Cresult_enc[medical_ds_3$A1Cresult == 'Norm'] <- 1
medical_ds_3$A1Cresult_enc[medical_ds_3$A1Cresult == '>7'] <- 2
medical_ds_3$A1Cresult_enc[medical_ds_3$A1Cresult == '>8'] <- 3

medical_ds_3$change_enc[medical_ds_3$change == 'Ch'] <- 1
medical_ds_3$change_enc[medical_ds_3$change == 'No'] <- 0




```

```{r encoding_medicien, MESSAGE = FALSE}
#"metformin","repaglinide",
#  "nateglinide","chlorpropamide","glimepiride","glipizide",
medical_ds_3$metformin_enc[medical_ds_3$metformin == 'Down'] <- 1
medical_ds_3$metformin_enc[medical_ds_3$metformin == 'No'] <- 2
medical_ds_3$metformin_enc[medical_ds_3$metformin == 'Steady'] <- 3
medical_ds_3$metformin_enc[medical_ds_3$metformin == 'Up'] <- 4


medical_ds_3$repaglinide_enc[medical_ds_3$repaglinide == 'Down'] <- 1
medical_ds_3$repaglinide_enc[medical_ds_3$repaglinide == 'No'] <- 2
medical_ds_3$repaglinide_enc[medical_ds_3$repaglinide == 'Steady'] <- 3
medical_ds_3$repaglinide_enc[medical_ds_3$repaglinide == 'Up'] <- 4

medical_ds_3$nateglinide_enc[medical_ds_3$nateglinide == 'Down'] <- 1
medical_ds_3$nateglinide_enc[medical_ds_3$nateglinide == 'No'] <- 2
medical_ds_3$nateglinide_enc[medical_ds_3$nateglinide == 'Steady'] <- 3
medical_ds_3$nateglinide_enc[medical_ds_3$nateglinide == 'Up'] <- 4

medical_ds_3$chlorpropamide_enc[medical_ds_3$chlorpropamide == 'Down'] <- 1
medical_ds_3$chlorpropamide_enc[medical_ds_3$chlorpropamide == 'No'] <- 2
medical_ds_3$chlorpropamide_enc[medical_ds_3$chlorpropamide == 'Steady'] <- 3
medical_ds_3$chlorpropamide_enc[medical_ds_3$chlorpropamide == 'Up'] <- 4

medical_ds_3$glimepiride_enc[medical_ds_3$glimepiride == 'Down'] <- 1
medical_ds_3$glimepiride_enc[medical_ds_3$glimepiride == 'No'] <- 2
medical_ds_3$glimepiride_enc[medical_ds_3$glimepiride == 'Steady'] <- 3
medical_ds_3$glimepiride_enc[medical_ds_3$glimepiride == 'Up'] <- 4

medical_ds_3$glipizide_enc[medical_ds_3$glipizide == 'Down'] <- 1
medical_ds_3$glipizide_enc[medical_ds_3$glipizide == 'No'] <- 2
medical_ds_3$glipizide_enc[medical_ds_3$glipizide == 'Steady'] <- 3
medical_ds_3$glipizide_enc[medical_ds_3$glipizide == 'Up'] <- 4


#"glyburide","pioglitazone","rosiglitazone",
#  "acarbose","miglitol","insulin","glyburide.metformin"
medical_ds_3$glyburide_enc[medical_ds_3$glyburide == 'Down'] <- 1
medical_ds_3$glyburide_enc[medical_ds_3$glyburide == 'No'] <- 2
medical_ds_3$glyburide_enc[medical_ds_3$glyburide == 'Steady'] <- 3
medical_ds_3$glyburide_enc[medical_ds_3$glyburide == 'Up'] <- 4

medical_ds_3$pioglitazone_enc[medical_ds_3$pioglitazone == 'Down'] <- 1
medical_ds_3$pioglitazone_enc[medical_ds_3$pioglitazone == 'No'] <- 2
medical_ds_3$pioglitazone_enc[medical_ds_3$pioglitazone == 'Steady'] <- 3
medical_ds_3$pioglitazone_enc[medical_ds_3$pioglitazone == 'Up'] <- 4

medical_ds_3$rosiglitazone_enc[medical_ds_3$rosiglitazone == 'Down'] <- 1
medical_ds_3$rosiglitazone_enc[medical_ds_3$rosiglitazone == 'No'] <- 2
medical_ds_3$rosiglitazone_enc[medical_ds_3$rosiglitazone == 'Steady'] <- 3
medical_ds_3$rosiglitazone_enc[medical_ds_3$rosiglitazone == 'Up'] <- 4


medical_ds_3$acarbose_enc[medical_ds_3$acarbose == 'Down'] <- 1
medical_ds_3$acarbose_enc[medical_ds_3$acarbose == 'No'] <- 2
medical_ds_3$acarbose_enc[medical_ds_3$acarbose == 'Steady'] <- 3
medical_ds_3$acarbose_enc[medical_ds_3$acarbose == 'Up'] <- 4

medical_ds_3$miglitol_enc[medical_ds_3$miglitol == 'Down'] <- 1
medical_ds_3$miglitol_enc[medical_ds_3$miglitol == 'No'] <- 2
medical_ds_3$miglitol_enc[medical_ds_3$miglitol == 'Steady'] <- 3
medical_ds_3$miglitol_enc[medical_ds_3$miglitol == 'Up'] <- 4

medical_ds_3$insulin_enc[medical_ds_3$insulin == 'Down'] <- 1
medical_ds_3$insulin_enc[medical_ds_3$insulin == 'No'] <- 2
medical_ds_3$insulin_enc[medical_ds_3$insulin == 'Steady'] <- 3
medical_ds_3$insulin_enc[medical_ds_3$insulin == 'Up'] <- 4

medical_ds_3$glyburide.metformin_enc[medical_ds_3$glyburide.metformin == 'Down'] <- 1
medical_ds_3$glyburide.metformin_enc[medical_ds_3$glyburide.metformin == 'No'] <- 2
medical_ds_3$glyburide.metformin_enc[medical_ds_3$glyburide.metformin == 'Steady'] <- 3
medical_ds_3$glyburide.metformin_enc[medical_ds_3$glyburide.metformin == 'Up'] <- 4

summary(medical_ds_3)
```

```{r diagnosis_code_1_encoding, MESSAGE=FALSE}
medical_ds_3$diag_1 <- as.numeric(medical_ds_3$diag_1)
#medical_ds_3$diag_1_enc <- 0
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 390 & medical_ds_3$diag_1 <= 459] <- 1
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 == 785] <- 1

#temp <- medical_ds_3 %>%
#  filter(diag_1_enc == 1 | diag_1_enc == 785)
#nrow(temp)

medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 460 & medical_ds_3$diag_1 <= 519] <- 2
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 == 786] <- 2

medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 520 & medical_ds_3$diag_1 <= 579] <- 3
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 == 787] <- 3

medical_ds_3$diag_1_enc[medical_ds_3$diag_1 == 250] <- 4

medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 800 & medical_ds_3$diag_1 <= 999] <- 5

medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 710 & medical_ds_3$diag_1 <= 739] <- 6

medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 580 & medical_ds_3$diag_1 <= 629] <- 7
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 == 788] <- 7

medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 140 & medical_ds_3$diag_1 <= 239] <- 8


medical_ds_3$diag_1_enc[medical_ds_3$diag_1 == 780 | medical_ds_3$diag_1 == 782 | medical_ds_3$diag_1 == 781 | medical_ds_3$diag_1 == 784] <- 9
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 790 & medical_ds_3$diag_1 <= 799] <- 9
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 240 & medical_ds_3$diag_1 <= 249] <- 9
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 251 & medical_ds_3$diag_1 <= 279] <- 9
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 680 & medical_ds_3$diag_1 <= 709] <- 9

medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 1 & medical_ds_3$diag_1 <= 139] <- 9
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 290 & medical_ds_3$diag_1 <= 319] <- 9


medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 280 & medical_ds_3$diag_1 <= 289] <- 9
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 320 & medical_ds_3$diag_1 <= 359] <- 9
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 630 & medical_ds_3$diag_1 <= 679] <- 9
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 360 & medical_ds_3$diag_1 <= 389] <- 9
medical_ds_3$diag_1_enc[medical_ds_3$diag_1 >= 740 & medical_ds_3$diag_1 <= 759] <- 9

summary(medical_ds_3$diag_1_enc)
summary(medical_ds_3$diag_1)
```

```{r}
temp <- medical_ds_3 %>%
  filter(is.na(diag_1_enc))
nrow(temp)
head(temp)
```


```{r diagnosis_code_2_encoding, MESSAGE=FALSE}
medical_ds_3$diag_2 <- as.numeric(medical_ds_3$diag_2)
#medical_ds_3$diag_2_enc <- 0
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 390 & medical_ds_3$diag_2 <= 459] <- 1
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 == 785] <- 1

medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 460 & medical_ds_3$diag_2 <= 519] <- 2
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 == 786] <- 2

medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 520 & medical_ds_3$diag_2 <= 579] <- 3
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 == 787] <- 3

medical_ds_3$diag_2_enc[medical_ds_3$diag_2 == 250] <- 4

medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 800 & medical_ds_3$diag_2 <= 999] <- 5

medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 710 & medical_ds_3$diag_2 <= 739] <- 6

medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 580 & medical_ds_3$diag_2 <= 629] <- 7
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 == 788] <- 7

medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 140 & medical_ds_3$diag_2 <= 239] <- 8


medical_ds_3$diag_2_enc[medical_ds_3$diag_2 == 780 | medical_ds_3$diag_2 == 782 | medical_ds_3$diag_2 == 781 | medical_ds_3$diag_2 == 784] <- 9
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 790 & medical_ds_3$diag_2 <= 799] <- 9
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 240 & medical_ds_3$diag_2 <= 249] <- 9
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 251 & medical_ds_3$diag_2 <= 279] <- 9
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 680 & medical_ds_3$diag_2 <= 709] <- 9

medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 1 & medical_ds_3$diag_2 <= 139] <- 9
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 290 & medical_ds_3$diag_2 <= 319] <- 9


medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 280 & medical_ds_3$diag_2 <= 289] <- 9
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 320 & medical_ds_3$diag_2 <= 359] <- 9
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 630 & medical_ds_3$diag_2 <= 679] <- 9
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 360 & medical_ds_3$diag_2 <= 389] <- 9
medical_ds_3$diag_2_enc[medical_ds_3$diag_2 >= 740 & medical_ds_3$diag_2 <= 759] <- 9

summary(medical_ds_3$diag_2_enc)
summary(medical_ds_3$diag_2)
```

```{r}
temp <- medical_ds_3 %>%
  filter(is.na(diag_2_enc))
nrow(temp)
head(temp)
```

```{r diagnosis_code_3_encoding, MESSAGE=FALSE}
medical_ds_3$diag_3 <- as.numeric(medical_ds_3$diag_3)
#medical_ds_3$diag_3_enc <- 0
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 390 & medical_ds_3$diag_3 <= 459] <- 1
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 == 785] <- 1

medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 460 & medical_ds_3$diag_3 <= 519] <- 2
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 == 786] <- 2

medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 520 & medical_ds_3$diag_3 <= 579] <- 3
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 == 787] <- 3

medical_ds_3$diag_3_enc[medical_ds_3$diag_3 == 250] <- 4

medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 800 & medical_ds_3$diag_3 <= 999] <- 5

medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 710 & medical_ds_3$diag_3 <= 739] <- 6

medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 580 & medical_ds_3$diag_3 <= 629] <- 7
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 == 788] <- 7

medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 140 & medical_ds_3$diag_3 <= 239] <- 8


medical_ds_3$diag_3_enc[medical_ds_3$diag_3 == 780 | medical_ds_3$diag_3 == 782 | medical_ds_3$diag_3 == 781 | medical_ds_3$diag_3 == 784] <- 9
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 790 & medical_ds_3$diag_3 <= 799] <- 9
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 240 & medical_ds_3$diag_3 <= 249] <- 9
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 251 & medical_ds_3$diag_3 <= 279] <- 9
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 680 & medical_ds_3$diag_3 <= 709] <- 9

medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 1 & medical_ds_3$diag_3 <= 139] <- 9
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 290 & medical_ds_3$diag_3 <= 319] <- 9


medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 280 & medical_ds_3$diag_3 <= 289] <- 9
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 320 & medical_ds_3$diag_3 <= 359] <- 9
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 630 & medical_ds_3$diag_3 <= 679] <- 9
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 360 & medical_ds_3$diag_3 <= 389] <- 9
medical_ds_3$diag_3_enc[medical_ds_3$diag_3 >= 740 & medical_ds_3$diag_3 <= 759] <- 9

medical_ds_3$readmitted_enc[medical_ds_3$readmitted == '<30'] <- "Yes"
medical_ds_3$readmitted_enc[medical_ds_3$readmitted == '>30'] <- "Yes"
medical_ds_3$readmitted_enc[medical_ds_3$readmitted == 'NO'] <- "No"

summary(medical_ds_3$diag_3_enc)
summary(medical_ds_3$diag_3)
```

```{r}
temp <- medical_ds_3 %>%
  filter(is.na(diag_3_enc))
nrow(temp)
head(temp)
```

```{r }
summary(medical_ds_3)
```


```{r}
temp <- medical_ds_3 %>%
  filter(is.na(max_glu_serum_enc ))
nrow(temp)
head(temp)
```

```{r final_dataset_1, MESSAGE=FALSE}
final_medical_ds <- medical_ds_3[,c(
  "age_ordinal", "race_enc", "gender_enc", "admission_type_id_enc","discharge_disposition_id_enc", "admission_source_id_enc", 
  "max_glu_serum_enc","A1Cresult_enc","change_enc",
  "metformin_enc","repaglinide_enc", "nateglinide_enc","chlorpropamide_enc","glimepiride_enc",
  "glipizide_enc","glyburide_enc","pioglitazone_enc","rosiglitazone_enc",
  "acarbose_enc","miglitol_enc","insulin_enc","glyburide.metformin_enc",
  "number_diagnoses",
  "time_in_hospital","num_lab_procedures",
  "num_procedures","num_medications","number_outpatient","number_emergency","number_inpatient",
  "diag_1_enc","diag_2_enc","diag_3_enc",
   "readmitted_enc"
  )]
summary(final_medical_ds)
```

```{r feature_engg, MESSAGE=FALSE}
final_medical_ds_1 <- final_medical_ds
final_medical_ds_1$diag_1_enc <- factor(final_medical_ds_1$diag_1_enc)
final_medical_ds_1$diag_2_enc <- factor(final_medical_ds_1$diag_2_enc)
final_medical_ds_1$diag_3_enc <- factor(final_medical_ds_1$diag_3_enc)
final_medical_ds_1$age_ordinal <- factor(final_medical_ds_1$age_ordinal)
final_medical_ds_1$race_enc <- factor(final_medical_ds_1$race_enc)
final_medical_ds_1$gender_enc <- factor(final_medical_ds_1$gender_enc)
final_medical_ds_1$admission_type_id_enc <- factor(final_medical_ds_1$admission_type_id_enc)
final_medical_ds_1$discharge_disposition_id_enc <- factor(final_medical_ds_1$discharge_disposition_id_enc)
final_medical_ds_1$admission_source_id_enc  <- factor(final_medical_ds_1$admission_source_id_enc )
final_medical_ds_1$change_enc <- factor(final_medical_ds_1$change_enc)

final_medical_ds_1$metformin_enc <- factor(final_medical_ds_1$metformin_enc)
final_medical_ds_1$repaglinide_enc <- factor(final_medical_ds_1$repaglinide_enc)
final_medical_ds_1$nateglinide_enc <- factor(final_medical_ds_1$nateglinide_enc)
final_medical_ds_1$chlorpropamide_enc <- factor(final_medical_ds_1$chlorpropamide_enc)
final_medical_ds_1$glimepiride_enc <- factor(final_medical_ds_1$glimepiride_enc)
final_medical_ds_1$glipizide_enc <- factor(final_medical_ds_1$glipizide_enc)
final_medical_ds_1$glyburide_enc <- factor(final_medical_ds_1$glyburide_enc)
final_medical_ds_1$pioglitazone_enc <- factor(final_medical_ds_1$pioglitazone_enc)


final_medical_ds_1$rosiglitazone_enc <- factor(final_medical_ds_1$rosiglitazone_enc)
final_medical_ds_1$acarbose_enc <- factor(final_medical_ds_1$acarbose_enc)
final_medical_ds_1$miglitol_enc <- factor(final_medical_ds_1$miglitol_enc)

final_medical_ds_1$glyburide.metformin_enc <- factor(final_medical_ds_1$glyburide.metformin_enc)

final_medical_ds_1$readmitted_enc <- factor(final_medical_ds_1$readmitted_enc)

summary(final_medical_ds_1)
```

```{r data_partition, MESSAGE=FALSE}
# split the data into training and (held-out) test sets
training_ind <- createDataPartition(final_medical_ds_1$readmitted_enc,
p = 0.75,
list = FALSE,
times = 1)
training_set <- final_medical_ds_1[training_ind, ]
test_set <- final_medical_ds_1[-training_ind, ]
summary(final_medical_ds_1)
```

```{r list_columns}
colnames(final_medical_ds_1)
```

```{r one_hot_encoding}
# these are the one-hot encodings of the categorical variables for both
# the training and test sets
onehot_encoder <- dummyVars(~ diag_1_enc + diag_2_enc + diag_3_enc, final_medical_ds_1[, c("diag_1_enc", "diag_2_enc", "diag_3_enc")])
onehot_enc_training <- predict(onehot_encoder, training_set[, c("diag_1_enc", "diag_2_enc", "diag_3_enc")])
training_set <- cbind(training_set, onehot_enc_training)
onehot_enc_test <- predict(onehot_encoder, test_set[, c("diag_1_enc", "diag_2_enc", "diag_3_enc")])
test_set <- cbind(test_set, onehot_enc_test)
test_set[, 23:30] <- scale(test_set[, 23:30], center = apply(training_set[, 23:30], 2, mean), scale = apply(training_set[, 23:30], 2, sd))
training_set[, 23:30] <- scale(training_set[, 23:30])
levels(training_set$readmitted_enc)[levels(training_set$readmitted_enc) == "Yes"] <- "Yes"
levels(training_set$readmitted_enc)[levels(training_set$readmitted_enc) == "No"] <- "No"
```

```{r}
#test_set$readmitted_1[test_set$readmitted == '<30'] <- "Yes"
#test_set$readmitted_1[test_set$readmitted == '>30'] <- "Yes"
#test_set$readmitted_1[test_set$readmitted == 'NO'] <- "No"
#summary(test_set$readmitted)
#head(test_set$readmitted_1)
#test_set[, 23:30]
#training_set$readmitted_enc
```

```{r random_forest}
modelLookup("rf")
recommended_mtry <- floor(sqrt(ncol(training_set[,-1*c(31:34)])))
rfGrid <- expand.grid(mtry = c(recommended_mtry-2, recommended_mtry, recommended_mtry+2))
```


```{r random_forest_1}

rfControl <- trainControl(method = "oob", classProbs = TRUE)
rf_onehot_model <- train(x = training_set[, -1*c(31:34)], y = training_set[, 34],
                  method = "rf",
                  tuneGrid = rfGrid,
                  trControl = rfControl,
                  ntree = 10,
                  importance = TRUE,
                  trace = FALSE)

```


```{r prediction}
test_set$prediction_onehot <- predict(rf_onehot_model, newdata = test_set[, -1*c(31:34)])
class_probabilities <- predict(rf_onehot_model, newdata = test_set[, -1*c(31:34)], type = "prob")
test_set$class_probabilities_onehot <- class_probabilities$Yes
```

```{r}
#test_set$class_probabilities_onehot
#test_set$readmitted
```

```{r evaluate}
head(test_set)
rocr_pred <- prediction(test_set$class_probabilities_onehot, test_set$readmitted_enc)
rocr_roc <- performance(rocr_pred, measure = "tpr", x.measure = "fpr")
plot(rocr_roc,
colorize = TRUE,
print.cutoffs.at = seq(0, 1, by = 0.1),
text.adj = c(-0.5, 1),
lwd = 2)
abline(a = 0, b = 1)

```


```{r auc_value}
rocr_auc <- performance(rocr_pred, measure = "auc")
auc <- rocr_auc@y.values[[1]]
auc
```

```{r calibration_curve}
calibration_curve <- calibration(readmitted_enc ~ class_probabilities_onehot,
data = test_set,
class = 1)
plot(calibration_curve)
```


```{r feature_importance}
rf_varImp <- varImp(rf_onehot_model, type = 2)
plot(rf_varImp, top = 25)
```

```{r list_important_features}
rf_varImp
```


```{r nueral_network}
modelLookup("nnet")
nnGrid <- expand.grid(size = 8:10, decay = 0.2)
nnControl <- trainControl(method = "repeatedcv",
              repeats = 5,
              number=10,
              classProbs = TRUE)

```

```{r, nnnet_subset}
training_subset_ds <- training_set[sample(nrow(training_set), 7500),]
nrow(training_subset_ds)

test_subset_ds <- test_set[sample(nrow(test_set), 2500),]
nrow(test_subset_ds)
```

```{r nueral_network_1}
nn_target_model <- train(x = training_subset_ds[, -1*c(31:34)], y = training_subset_ds[, 34],
method = "nnet",
tuneGrid = nnGrid,
trControl = nnControl,
trace = FALSE)
```


```{r neural_network_2}
test_subset_ds$prediction_target <- predict(nn_target_model,newdata = test_subset_ds[, -1*c(31:34)])
class_probabilities <- predict(nn_target_model, newdata = test_subset_ds[, -1*c(31:34)], type = "prob")
test_subset_ds$class_probabilities_target <- class_probabilities$Yes
```


```{r nueral_network_2}
rocr_pred <- prediction(test_subset_ds$class_probabilities_target, test_subset_ds$readmitted_enc)
rocr_roc <- performance(rocr_pred, measure = "tpr", x.measure = "fpr")
plot(rocr_roc,
colorize = TRUE,
print.cutoffs.at = seq(0, 1, by = 0.1),
text.adj = c(-0.5, 1),
lwd = 2)
abline(a = 0, b = 1)
```

```{r nueral_network_2}
rocr_auc <- performance(rocr_pred, measure = "auc")
auc <- rocr_auc@y.values[[1]]
auc
```